baseURL = "https://alphacoder.xyz/"
languageCode = "en-us"
title = "Alpha Coder"
theme = "diary"

# Pagination
paginate = 10
paginatePath = "page"

# Google analytics
googleAnalytics = "UA-82728104-5"

# Copyright
copyright = "Copyright 2020 to ∞. Try Catch Finally Solutions Ltd. All rights reserved."

# Taxonomies
[taxonomies]
    tag = "tags"

# Menu
[menu]
    # Header
    [[menu.main]]
        url = "/blog/"
        name = "Blog"
        weight = 1
    [[menu.main]]
        url = "https://courses.alphacoder.xyz"
        name = "Courses"
        weight = 2
    [[menu.main]]
        url = "https://community.alphacoder.xyz"
        name = "Community"
        weight = 3
    [[menu.main]]
        url = "/musings/"
        name = "Musings"
        weight = 4
    [[menu.main]]
        url = "https://tinyletter.com/nicholaskajoh"
        name = "Newsletter"
        weight = 5

    [[menu.footer]]
        url = "https://twitter.com/AlphaCoderXYZ"
        name = "Twitter"
        weight = 1
    [[menu.footer]]
        url = "https://www.linkedin.com/company/alphacoder"
        name = "LinkedIn"
        weight = 2
    [[menu.footer]]
        url = "mailto:support@alphacoder.xyz"
        name = "Email"
        weight = 3
    [[menu.footer]]
        url = "/blog/index.xml"
        name = "RSS"
        weight = 4

# SEO
enableRobotsTXT = true
canonifyURLs = true

# Links format
[permalinks]
    blog = "/:slug/"
    tags = "/tag/:slug/"
    musings = "/:slug/"

[params]
    enableReadingTime = true
    favicon = "/images/alpha-coder-logo-v1-small.png"
    disqusShortname = "alphacoderxyz"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
