baseURL = "http://alphacoder.xyz/"
languageCode = "en-gb"
title = "Alpha Coder"
theme = "simple-hugo-theme"

# Pagination
paginate = 25
paginatePath = "page"

# Google analytics
googleAnalytics = "UA-82728104-5"

disqusShortname = "alphacoderxyz"

# Copyright
copyright = "© Copyright 2020 to ∞. Try Catch Finally Solutions Ltd. All rights reserved."

# Highlighting
pygmentsCodefences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsoptions = "linenos=table"
pygmentsStyle = "perldoc"

# Taxonomies
[taxonomies]
    tag = "tags"

# Menu
[menu]
    # Header
    [[menu.main]]
        url = "/blog/"
        name = "Blog"
        weight = 1
    [[menu.main]]
        url = "https://courses.alphacoder.xyz"
        name = "Courses"
        weight = 2
    [[menu.main]]
        url = "https://community.alphacoder.xyz"
        name = "Community"
        weight = 3

    # Footer
    [[menu.footer]]
        url = "https://twitter.com/AlphaCoderXYZ"
        name = "Twitter"
        weight = 1
    [[menu.footer]]
        url = "https://www.linkedin.com/company/alphacoder"
        name = "LinkedIn"
        weight = 2
    [[menu.footer]]
        url = "mailto:support@alphacoder.xyz"
        name = "Email"
        weight = 3
    [[menu.footer]]
        url = "/blog/index.xml"
        name = "RSS"
        weight = 4

# SEO
enableRobotsTXT = true
canonifyURLs = true

# Links format
[permalinks]
    blog = "/:slug/"
    tags = "/tag/:slug/"