baseURL = "https://alphacoder.xyz/"
languageCode = "en-us"
title = "Alpha Coder"
theme = "diary"

# Pagination
paginate = 10
paginatePath = "page"

# Google analytics
# googleAnalytics = "UA-82728104-5"

# Copyright
copyright = "Copyright 2017 to ∞. Nicholas Kajoh. All rights reserved."

# Taxonomies
[taxonomies]
    tag = "tags"

# Menu
[menu]
    # Header
    [[menu.main]]
        url = "/blog/"
        name = "Blog"
        weight = 1
    [[menu.main]]
        url = "https://codereviewclub.com"
        name = "Code Review Club"
        weight = 2
    [[menu.main]]
        url = "https://www.youtube.com/channel/UC1vg_0J9BGfahmc7flbiwJw"
        name = "Videos"
        weight = 3
    [[menu.main]]
        url = "https://tinyletter.com/nicholaskajoh"
        name = "Newsletter"
        weight = 4

    [[menu.footer]]
        url = "https://twitter.com/AlphaCoderXYZ"
        name = "Twitter"
        weight = 1
    [[menu.footer]]
        url = "mailto:support@alphacoder.xyz"
        name = "Email"
        weight = 2
    [[menu.footer]]
        url = "/blog/index.xml"
        name = "RSS"
        weight = 3

# SEO
enableRobotsTXT = true
canonifyURLs = true

# Links format
[permalinks]
    blog = "/:slug/"
    tags = "/tag/:slug/"

[params]
    favicon = "/images/alpha-coder-logo-v1-small.png"
    disqusShortname = "alphacoderxyz"
    enablePlausible = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
