baseURL = "http://alphacoder.xyz/"
languageCode = "en-gb"
title = "Alpha Coder"
theme = "simple-hugo-theme"

# Pagination
paginate = 25
paginatePath = "page"

# Google analytics
googleAnalytics = "UA-82728104-5"

disqusShortname = "alphacoderxyz"

# Copyright
copyright = "© Nicholas Kajoh"

# Highlighting
pygmentsCodefences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsoptions = "linenos=table"
pygmentsStyle = "perldoc"

# Taxonomies
[taxonomies]
    tag = "tags"

# Menu
[menu]
    # Header
    [[menu.main]]
        url = "/blog/"
        name = "Blog"
        weight = 1
    [[menu.main]]
        url = "/courses/"
        name = "Courses"
        weight = 2
    [[menu.main]]
        url = "http://bit.ly/nksnewsletter"
        name = "Newsletter"
        weight = 3

    # Footer
    [[menu.footer]]
        url = "http://twitter.com/nicholaskajoh"
        name = "Twitter"
        weight = 1
    [[menu.footer]]
        url = "https://github.com/nicholaskajoh"
        name = "GitHub"
        weight = 2
    [[menu.footer]]
        url = "http://buymeacoff.ee/nicholaskajoh"
        name = "Buy me a coffee"
        weight = 3
    [[menu.footer]]
        url = "/post/index.xml"
        name = "RSS"
        weight = 4

# SEO
enableRobotsTXT = true
canonifyURLs = true

# Links format
[permalinks]
    blog = "/:slug/"
    tags = "/tag/:slug/"